In [1]:
import requests

key = 'wInXCagNrKUflNoceXWc6O4u5lUcvCHnYyep2Vfo'
query = 'climate change'
url = f'https://images-api.nasa.gov/search?q={query}'

r = requests.get(url)

In [2]:
r

In [3]:
parsed = r.json()

In [4]:
parsed.keys()

dict_keys(['collection'])

In [5]:
articles = parsed['collection']

In [6]:
type(articles)

dict

In [7]:
type(articles['items'])

list

In [8]:
type(articles['items'][0]['data'])

list

In [9]:
articles.keys()

dict_keys(['version', 'href', 'items', 'metadata', 'links'])

In [10]:
articles

{'version': '1.1',
 'href': 'http://images-api.nasa.gov/search?q=climate%20change',
 'items': [{'href': 'https://images-assets.nasa.gov/video/NASA Administrator Bill Nelson - Answering Climate Change from Above/collection.json',
   'data': [{'center': 'HQ',
     'date_created': '2024-09-30T00:00:00Z',
     'description': 'NASA Administrator Bill Nelson speaks to the power of NASA’s climate-related data to help the world understand climate change and take action.   “The challenge of the climate crisis is here and now. Let’s answer it—from above.”    Most of what humanity knows about our changing planet comes from NASA’s more than two-dozen satellites and instruments—and from the agency’s observations for over 60 years.',
     'keywords': ['NASA', 'NASA Administrator Bill Nelson', 'Climate Change'],
     'media_type': 'video',
     'nasa_id': 'NASA Administrator Bill Nelson - Answering Climate Change from Above',
     'title': 'NASA Administrator Bill Nelson | Answering Climate Change from Above'}],
   'links': [{'href': 'https://images-assets.nasa.gov/video/NASA Administrator Bill Nelson - Answering Climate Change from Above/NASA Administrator Bill Nelson - Answering Climate Change from Above~large.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 800,
     'size': 36000,
     'height': 450},
    {'href': 'https://images-assets.nasa.gov/video/NASA Administrator Bill Nelson - Answering Climate Change from Above/NASA Administrator Bill Nelson - Answering Climate Change from Above~medium.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 400,
     'size': 15000,
     'height': 225},
    {'href': 'https://images-assets.nasa.gov/video/NASA Administrator Bill Nelson - Answering Climate Change from Above/NASA Administrator Bill Nelson - Answering Climate Change from Above~small.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 200,
     'size': 7000,
     'height': 112},
    {'href': 'https://images-assets.nasa.gov/video/NASA Administrator Bill Nelson - Answering Climate Change from Above/NASA Administrator Bill Nelson - Answering Climate Change from Above~thumb.jpg',
     'rel': 'preview',
     'render': 'image',
     'width': 300,
     'size': 11000,
     'height': 168},
    {'href': 'https://images-assets.nasa.gov/video/NASA Administrator Bill Nelson - Answering Climate Change from Above/NASA Administrator Bill Nelson - Answering Climate Change from Above.srt',
     'rel': 'captions'}]},
  {'href': 'https://images-assets.nasa.gov/video/Is Climate Change the Same as Global Warming_ - Horizontal Video/collection.json',
   'data': [{'center': 'HQ',
     'date_created': '2023-07-27T00:00:00Z',
     'description': 'Is climate change the same as global warming? They’re not exactly the same, but they are related. The warming of Earth — or global warming — is just one factor that makes up a range of changes that are happening to our planet, which is climate change. NASA scientist Dr. Yolanda Shea explains more.',
     'keywords': ['We Asked A NASA Expert',
      'Climate Change',
      'Global Warming',
      'Earth',
      'Greenhouse Gases'],
     'media_type': 'video',
     'nasa_id': 'Is Climate Change the Same as Global Warming_ - Horizontal Video',
     'title': 'Is Climate Change the Same as Global Warming? We Asked A NASA Expert '}],
   'links': [{'href': 'https://images-assets.nasa.gov/video/Is Climate Change the Same as Global Warming_ - Horizontal Video/Is Climate Change the Same as Global Warming_ - Horizontal Video~large.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 800,
     'size': 28000,
     'height': 450},
    {'href': 'https://images-assets.nasa.gov/video/Is Climate Change the Same as Global Warming_ - Horizontal Video/Is Climate Change the Same as Global Warming_ - Horizontal Video~medium.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 400,
     'size': 11000,
     'height': 225},
    {'href': 'https://images-assets.nasa.gov/video/Is Climate Change the Same as Global Warming_ - Horizontal Video/Is Climate Change the Same as Global Warming_ - Horizontal Video~small.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 200,
     'size': 4200,
     'height': 112},
    {'href': 'https://images-assets.nasa.gov/video/Is Climate Change the Same as Global Warming_ - Horizontal Video/Is Climate Change the Same as Global Warming_ - Horizontal Video~thumb.jpg',
     'rel': 'preview',
     'render': 'image',
     'width': 300,
     'size': 6500,
     'height': 168},
    {'href': 'https://images-assets.nasa.gov/video/Is Climate Change the Same as Global Warming_ - Horizontal Video/Is Climate Change the Same as Global Warming_ - Horizontal Video.srt',
     'rel': 'captions'}]},
  {'href': 'https://images-assets.nasa.gov/video/GSFC_20131203_AACS_m11426_Affect_Humans/collection.json',
   'data': [{'album': ['Climate'],
     'center': 'GSFC',
     'date_created': '2013-12-03T00:00:00Z',
     'description': 'How does climate change affect humans? That\'s the question we asked Tom Wagner, Program Scientist for Cryospheric Research at NASA. In four different ways, he says, from rainfall patterns and sea levels rising to food production and ocean acidification. First, "as the planet warms up, we\'re going to redistribute rainfall, which is going to affect our water resources and parts of North America may get a lot drier."  Second, "as the polar ice melts, sea levels are going to rise." The world\'s major cities, and a lot of people, are right on the coasts and rising sea levels are going to impact them.  Third, thinking about food, the "distributions where we can grow food are going to change as the planet warms up." So the range over which you can grow corn and other crops will change.  Fourth, says Tom Wagner, "the oceans are going to get more acidic as more CO2 dissolves in them." There are untold ramifications from that, including the possibility of radically altering the food web in the ocean, "which can affect everything from the composition of the atmosphere to the ability of the oceans to provide food for us."',
     'description_508': "Will climate change affect humans? NASA's Tom Wagner says yes, in four different ways.",
     'keywords': ['Precipitation',
      'Sea Level Rise',
      'Climate Change',
      'Food Supply',
      'Earth'],
     'location': 'Goddard Space Flight Center',
     'media_type': 'video',
     'nasa_id': 'GSFC_20131203_AACS_m11426_Affect_Humans',
     'secondary_creator': 'Matthew R. Radcliff, Silvia Stoyanova, Tom Wagner',
     'title': 'Ask A Climate Scientist - Climate Change and Humans'}],
   'links': [{'href': 'https://images-assets.nasa.gov/video/GSFC_20131203_AACS_m11426_Affect_Humans/GSFC_20131203_AACS_m11426_Affect_Humans~large.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 800,
     'size': 35000,
     'height': 450},
    {'href': 'https://images-assets.nasa.gov/video/GSFC_20131203_AACS_m11426_Affect_Humans/GSFC_20131203_AACS_m11426_Affect_Humans~medium.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 400,
     'size': 15000,
     'height': 225},
    {'href': 'https://images-assets.nasa.gov/video/GSFC_20131203_AACS_m11426_Affect_Humans/GSFC_20131203_AACS_m11426_Affect_Humans~small.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 200,
     'size': 6900,
     'height': 112},
    {'href': 'https://images-assets.nasa.gov/video/GSFC_20131203_AACS_m11426_Affect_Humans/GSFC_20131203_AACS_m11426_Affect_Humans~thumb.jpg',
     'rel': 'preview',
     'render': 'image',
     'width': 300,
     'size': 11000,
     'height': 168},
    {'href': 'https://images-assets.nasa.gov/video/GSFC_20131203_AACS_m11426_Affect_Humans/GSFC_20131203_AACS_m11426_Affect_Humans.vtt',
     'rel': 'captions'}]},
  {'href': 'https://images-assets.nasa.gov/video/GSFC_20161116_Climate_m12426_Change/collection.json',
   'data': [{'album': ['Climate'],
     'center': 'GSFC',
     'date_created': '2016-11-16T00:00:00Z',
     'description': 'Researchers and city officials from two of the world’s major metropolises, New York City and Rio de Janeiro, are coming together to share their insights and solutions against specific climate risks afflicting both their cities— sea level rise, increased temperatures and changes in water quality.',
     'description_508': 'Researchers and city officials from two of the world’s major metropolises, New York City and Rio de Janeiro, are coming together to share their insights and solutions against specific climate risks afflicting both their cities— sea level rise, increased temperatures and changes in water quality.',
     'keywords': ['Earth',
      'Landsat',
      'New York City',
      'Earth Science',
      'Climate Change',
      'MODIS'],
     'location': 'Goddard Space Flight Center',
     'media_type': 'video',
     'nasa_id': 'GSFC_20161116_Climate_m12426_Change',
     'secondary_creator': 'Kathryn Mersmann, Cynthia Rosenzweig, Dalia B. Kirschbaum, Kasha Patel',
     'title': 'NASA Scientists Help Citites Prepare for Climate Change'}],
   'links': [{'href': 'https://images-assets.nasa.gov/video/GSFC_20161116_Climate_m12426_Change/GSFC_20161116_Climate_m12426_Change~large.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 800,
     'size': 43000,
     'height': 450},
    {'href': 'https://images-assets.nasa.gov/video/GSFC_20161116_Climate_m12426_Change/GSFC_20161116_Climate_m12426_Change~medium.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 400,
     'size': 16000,
     'height': 225},
    {'href': 'https://images-assets.nasa.gov/video/GSFC_20161116_Climate_m12426_Change/GSFC_20161116_Climate_m12426_Change~small.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 200,
     'size': 5800,
     'height': 112},
    {'href': 'https://images-assets.nasa.gov/video/GSFC_20161116_Climate_m12426_Change/GSFC_20161116_Climate_m12426_Change~thumb.jpg',
     'rel': 'preview',
     'render': 'image',
     'width': 300,
     'size': 12000,
     'height': 168},
    {'href': 'https://images-assets.nasa.gov/video/GSFC_20161116_Climate_m12426_Change/GSFC_20161116_Climate_m12426_Change.vtt',
     'rel': 'captions'}]},
  {'href': 'https://images-assets.nasa.gov/video/GSFC_20130918_AACS_m11356_Food/collection.json',
   'data': [{'album': ['Climate'],
     'center': 'GSFC',
     'date_created': '2013-09-18T00:00:00Z',
     'description': "Will climate change drastically reduce our food production, or will it change what we produce? This question was posed to Goddard Space Flight Center's Molly Brown as part of NASA's Ask A Climate Scientist campaign.",
     'description_508': "Will climate change drastically reduce our food production, or will it change what we produce? This question was posed to Goddard Space Flight Center's Molly Brown as part of NASA's Ask A Climate Scientist campaign.",
     'keywords': ['Climate Change', 'Food Supply', 'Earth'],
     'location': 'Goddard Space Flight Center',
     'media_type': 'video',
     'nasa_id': 'GSFC_20130918_AACS_m11356_Food',
     'photographer': 'Robert Andreoli, John Caldwell',
     'secondary_creator': 'Matthew R. Radcliff, Molly Brown, Patrick Lynch',
     'title': 'Ask A Climate Scientist - Food Production'}],
   'links': [{'href': 'https://images-assets.nasa.gov/video/GSFC_20130918_AACS_m11356_Food/GSFC_20130918_AACS_m11356_Food~large.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 800,
     'size': 25000,
     'height': 450},
    {'href': 'https://images-assets.nasa.gov/video/GSFC_20130918_AACS_m11356_Food/GSFC_20130918_AACS_m11356_Food~medium.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 400,
     'size': 12000,
     'height': 225},
    {'href': 'https://images-assets.nasa.gov/video/GSFC_20130918_AACS_m11356_Food/GSFC_20130918_AACS_m11356_Food~small.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 200,
     'size': 5100,
     'height': 112},
    {'href': 'https://images-assets.nasa.gov/video/GSFC_20130918_AACS_m11356_Food/GSFC_20130918_AACS_m11356_Food~thumb.jpg',
     'rel': 'preview',
     'render': 'image',
     'width': 300,
     'size': 8100,
     'height': 168},
    {'href': 'https://images-assets.nasa.gov/video/GSFC_20130918_AACS_m11356_Food/GSFC_20130918_AACS_m11356_Food.vtt',
     'rel': 'captions'}]},
  {'href': 'https://images-assets.nasa.gov/image/MSFC-201901694/collection.json',
   'data': [{'center': 'MSFC',
     'date_created': '2019-12-04T00:00:00Z',
     'description': 'NASA climatologist Gary Jedlovec, a member of the Earth Science team in Marshall Space Flight Center’s Science and Technology Office, discusses the satellite technology and ground-based tools used to record and trend regional and global climate changes over the past century and to provide forecast models looking 100 years into the future. Jedlovec and his team, which partners with National Oceanic and Atmospheric Association researchers and their colleagues around the world, spoke to the Marshall “Green Team” -- environmental engineers and support personnel who help guide Marshall’s focus on safer, more cost-efficient energy use. The Green Team, led by Marshall Sustainability Engineer Donna Leach of the Environmental Engineering & Occupational Health Office, currently is preparing activities and outreach for Earth Day 2020, set for next April.',
     'keywords': ['MSFC', 'Gary Jedlovec', 'Green Team', 'Climate Change'],
     'location': 'MSFC 4249',
     'media_type': 'image',
     'nasa_id': 'MSFC-201901694',
     'photographer': 'Fred Deaton',
     'title': 'Gary Jedlovec Climate Change Presentation to Green Team'}],
   'links': [{'href': 'https://images-assets.nasa.gov/image/MSFC-201901694/MSFC-201901694~medium.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 1280,
     'size': 127000,
     'height': 853},
    {'href': 'https://images-assets.nasa.gov/image/MSFC-201901694/MSFC-201901694~small.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 640,
     'size': 42000,
     'height': 426},
    {'href': 'https://images-assets.nasa.gov/image/MSFC-201901694/MSFC-201901694~thumb.jpg',
     'rel': 'preview',
     'render': 'image',
     'width': 640,
     'size': 42000,
     'height': 426},
    {'href': 'https://images-assets.nasa.gov/image/MSFC-201901694/MSFC-201901694~large.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 1920,
     'size': 253000,
     'height': 1280},
    {'href': 'https://images-assets.nasa.gov/image/MSFC-201901694/MSFC-201901694~orig.tif',
     'rel': 'canonical',
     'render': 'image',
     'height': 5504,
     'width': 8256,
     'size': 61000000}]},
  {'href': 'https://images-assets.nasa.gov/image/PIA03179/collection.json',
   'data': [{'center': 'JPL',
     'date_created': '2001-12-11T23:09:44Z',
     'description': 'MOC Observes Changes in the South Polar Cap: Evidence for Recent Climate Change on Mars',
     'description_508': 'MOC Observes Changes in the South Polar Cap: Evidence for Recent Climate Change on Mars',
     'keywords': ['Mars', 'Mars Global Surveyor MGS'],
     'media_type': 'image',
     'nasa_id': 'PIA03179',
     'secondary_creator': 'NASA/JPL/MSSS',
     'title': 'MOC Observes Changes in the South Polar Cap: Evidence for Recent Climate Change on Mars'}],
   'links': [{'href': 'https://images-assets.nasa.gov/image/PIA03179/PIA03179~thumb.jpg',
     'rel': 'preview',
     'render': 'image',
     'width': 1048,
     'size': 118000,
     'height': 524},
    {'href': 'https://images-assets.nasa.gov/image/PIA03179/PIA03179~orig.jpg',
     'rel': 'canonical',
     'render': 'image',
     'height': 524,
     'width': 1048,
     'size': 120000}]},
  {'href': 'https://images-assets.nasa.gov/image/NHQ202408070019/collection.json',
   'data': [{'album': ['20240807_NASA_HQ_ECR_CCRI'],
     'center': 'HQ',
     'date_created': '2024-08-07T00:00:00Z',
     'description': 'Members of the Climate Change Research Initiative (CCRI) cohort discuss their research during a poster session, Wednesday, Aug. 7, 2024, at the Mary W. Jackson NASA Headquarters building in Washington, DC. The Earth Science Division’s Early Career Research Program’s Climate Change Research Initiative (CCRI) is a year-long STEM engagement and experiential learning opportunity for educators and students from high school to graduate level. Photo Credit: (NASA/Joel Kowsky)',
     'keywords': ['Climate Change Research Initiative (CCRI)',
      'DC',
      'Mary W. Jackson NASA Headquarters',
      'NASA Early Career Research Program (ECR)',
      'Washington'],
     'location': 'NASA Headquarters',
     'media_type': 'image',
     'nasa_id': 'NHQ202408070019',
     'photographer': 'NASA/Joel Kowsky',
     'title': 'NASA Early Career Research Program - Climate Change Research Ini'}],
   'links': [{'href': 'https://images-assets.nasa.gov/image/NHQ202408070019/NHQ202408070019~medium.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 1280,
     'size': 183000,
     'height': 853},
    {'href': 'https://images-assets.nasa.gov/image/NHQ202408070019/NHQ202408070019~small.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 640,
     'size': 61000,
     'height': 426},
    {'href': 'https://images-assets.nasa.gov/image/NHQ202408070019/NHQ202408070019~thumb.jpg',
     'rel': 'preview',
     'render': 'image',
     'width': 640,
     'size': 61000,
     'height': 426},
    {'href': 'https://images-assets.nasa.gov/image/NHQ202408070019/NHQ202408070019~large.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 1920,
     'size': 374000,
     'height': 1280},
    {'href': 'https://images-assets.nasa.gov/image/NHQ202408070019/NHQ202408070019~orig.jpg',
     'rel': 'canonical',
     'render': 'image',
     'height': 5504,
     'width': 8256,
     'size': 37748736}]},
  {'href': 'https://images-assets.nasa.gov/image/NHQ202408070014/collection.json',
   'data': [{'album': ['20240807_NASA_HQ_ECR_CCRI'],
     'center': 'HQ',
     'date_created': '2024-08-07T00:00:00Z',
     'description': 'Members of the Climate Change Research Initiative (CCRI) cohort discuss their research during a poster session, Wednesday, Aug. 7, 2024, at the Mary W. Jackson NASA Headquarters building in Washington, DC. The Earth Science Division’s Early Career Research Program’s Climate Change Research Initiative (CCRI) is a year-long STEM engagement and experiential learning opportunity for educators and students from high school to graduate level. Photo Credit: (NASA/Joel Kowsky)',
     'keywords': ['Climate Change Research Initiative (CCRI)',
      'DC',
      'Mary W. Jackson NASA Headquarters',
      'NASA Early Career Research Program (ECR)',
      'Washington'],
     'location': 'NASA Headquarters',
     'media_type': 'image',
     'nasa_id': 'NHQ202408070014',
     'photographer': 'NASA/Joel Kowsky',
     'title': 'NASA Early Career Research Program - Climate Change Research Ini'}],
   'links': [{'href': 'https://images-assets.nasa.gov/image/NHQ202408070014/NHQ202408070014~medium.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 1280,
     'size': 220000,
     'height': 1008},
    {'href': 'https://images-assets.nasa.gov/image/NHQ202408070014/NHQ202408070014~small.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 640,
     'size': 61000,
     'height': 504},
    {'href': 'https://images-assets.nasa.gov/image/NHQ202408070014/NHQ202408070014~thumb.jpg',
     'rel': 'preview',
     'render': 'image',
     'width': 640,
     'size': 61000,
     'height': 504},
    {'href': 'https://images-assets.nasa.gov/image/NHQ202408070014/NHQ202408070014~large.jpg',
     'rel': 'alternate',
     'render': 'image',
     'width': 1920,
     'size': 488000,
     'height': 1512},
    {'href': 'https://images-assets.nasa.gov/image/NHQ202408070014/NHQ202408070014~orig.jpg',

In [7]:
items = articles['items']

In [12]:
type(items)

list

In [13]:
items[0]

{'href': 'https://images-assets.nasa.gov/video/NASA Administrator Bill Nelson - Answering Climate Change from Above/collection.json',
 'data': [{'center': 'HQ',
   'date_created': '2024-09-30T00:00:00Z',
   'description': 'NASA Administrator Bill Nelson speaks to the power of NASA’s climate-related data to help the world understand climate change and take action.   “The challenge of the climate crisis is here and now. Let’s answer it—from above.”    Most of what humanity knows about our changing planet comes from NASA’s more than two-dozen satellites and instruments—and from the agency’s observations for over 60 years.',
   'keywords': ['NASA', 'NASA Administrator Bill Nelson', 'Climate Change'],
   'media_type': 'video',
   'nasa_id': 'NASA Administrator Bill Nelson - Answering Climate Change from Above',
   'title': 'NASA Administrator Bill Nelson | Answering Climate Change from Above'}],
 'links': [{'href': 'https://images-assets.nasa.gov/video/NASA Administrator Bill Nelson - Answering Climate Change from Above/NASA Administrator Bill Nelson - Answering Climate Change from Above~large.jpg',
   'rel': 'alternate',
   'render': 'image',
   'width': 800,
   'size': 36000,
   'height': 450},
  {'href': 'https://images-assets.nasa.gov/video/NASA Administrator Bill Nelson - Answering Climate Change from Above/NASA Administrator Bill Nelson - Answering Climate Change from Above~medium.jpg',
   'rel': 'alternate',
   'render': 'image',
   'width': 400,
   'size': 15000,
   'height': 225},
  {'href': 'https://images-assets.nasa.gov/video/NASA Administrator Bill Nelson - Answering Climate Change from Above/NASA Administrator Bill Nelson - Answering Climate Change from Above~small.jpg',
   'rel': 'alternate',
   'render': 'image',
   'width': 200,
   'size': 7000,
   'height': 112},
  {'href': 'https://images-assets.nasa.gov/video/NASA Administrator Bill Nelson - Answering Climate Change from Above/NASA Administrator Bill Nelson - Answering Climate Change from Above~thumb.jpg',
   'rel': 'preview',
   'render': 'image',
   'width': 300,
   'size': 11000,
   'height': 168},
  {'href': 'https://images-assets.nasa.gov/video/NASA Administrator Bill Nelson - Answering Climate Change from Above/NASA Administrator Bill Nelson - Answering Climate Change from Above.srt',
   'rel': 'captions'}]}

In [14]:
type(items[0])

dict

In [15]:
items[0].keys()

dict_keys(['href', 'data', 'links'])

In [16]:
items[0]['data']

[{'center': 'HQ',
  'date_created': '2024-09-30T00:00:00Z',
  'description': 'NASA Administrator Bill Nelson speaks to the power of NASA’s climate-related data to help the world understand climate change and take action.   “The challenge of the climate crisis is here and now. Let’s answer it—from above.”    Most of what humanity knows about our changing planet comes from NASA’s more than two-dozen satellites and instruments—and from the agency’s observations for over 60 years.',
  'keywords': ['NASA', 'NASA Administrator Bill Nelson', 'Climate Change'],
  'media_type': 'video',
  'nasa_id': 'NASA Administrator Bill Nelson - Answering Climate Change from Above',
  'title': 'NASA Administrator Bill Nelson | Answering Climate Change from Above'}]

In [17]:
type(items[0]['data'])

list

In [18]:
items[0]['data'][0]['keywords']

['NASA', 'NASA Administrator Bill Nelson', 'Climate Change']

In [8]:
titles = []
datesCreated = []
keywords = []
mediaTypes = []
descriptions = []
nasaIds = []
links = []

for i in items:
    title = (i['data'][0]['title'])
    titles.append(title)

for i in items:
    dateCreated = (i['data'][0]['date_created'])
    datesCreated.append(dateCreated)

for i in items:
    mediaType = (i['data'][0]['media_type'])
    mediaTypes.append(mediaType)

for i in items:
    description = (i['data'][0]['description'])
    descriptions.append(description)

for i in items:
    nasaId = (i['data'][0]['nasa_id'])
    nasaIds.append(nasaId)

for i in items:
    try:
        keyword = i['data'][0]['keywords']
        keywords.append(keyword)
    except:
        keyword = 'n/a'
        keywords.append(keyword)

for i in items:
    try:
        link = i['links']
        links.append(link)
    except:
        link = 'n/a'
        links.append(link)

In [9]:
print(len(titles), len(datesCreated), len(keywords), len(mediaTypes), len(descriptions), len(nasaIds), len(links))

100 100 100 100 100 100 100

In [21]:
titles

['NASA Administrator Bill Nelson | Answering Climate Change from Above',
 'Is Climate Change the Same as Global Warming? We Asked A NASA Expert ',
 'Ask A Climate Scientist - Climate Change and Humans',
 'NASA Scientists Help Citites Prepare for Climate Change',
 'Ask A Climate Scientist - Food Production',
 'Gary Jedlovec Climate Change Presentation to Green Team',
 'MOC Observes Changes in the South Polar Cap: Evidence for Recent Climate Change on Mars',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'IPCC Projections of Temperature and Precipitation in the 21st Century',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'NASA Early Career Research Program - Climate Change Research Ini',
 'A Summer ABoVE the Warming Arctic',
 'Record-Breaking Climate Trends 2016 – Rising Temperatures and Shrinking Sea Ice',
 'NASA Science Live: Climate Edition - Extreme Weather [Episode 57]',
 'Ask A Climate Scientist - Lagging CO2',
 'NASA Science Live: The Summer of Record-Breaking Heat [Episode 48]',
 "NASA Tracks the Future of Asia's Glaciers",
 'Vice President Kamala Harris Visited NASA’s Goddard Space Flight Center - Wrap Package',
 'NASA ScienceCasts: Station Science 101 - Earth Observation from the Space Station',
 'Salt of the Earth',
 'KSC-2011-2637',
 'KSC-2011-2724',
 'KSC-2011-2726',
 'KSC-2011-2624',
 'KSC-2011-2638',
 'KSC-2011-2635',
 'KSC-2011-2626',
 'KSC-2011-2633',
 'KSC-2011-2629',
 'KSC-2011-2728',
 'KSC-2011-2727',
 'KSC-2011-2627',
 'KSC-2011-2634',
 'KSC-2011-2628',
 'KSC-2011-2636',
 'KSC-2011-2632',
 'KSC-2011-2625',
 'KSC-2011-2725',
 'KSC-2011-2631',
 'KSC-2011-2630',
 'KSC-2011-2623',
 'Landsat Observes Barrier Islands',
 'Planetary Scientist Profile: Emily Wilson',
 'Details of Arctic Greening in North America',
 'KSC-2011-2195',
 'KSC-2011-2191',
 'KSC-2011-2449',
 'KSC-2011-2456',
 'KSC-2011-2193',
 'KSC-2011-2194',
 'KSC-2011-2451',
 'KSC-2011-2454',
 'KSC-2011-2189',
 'KSC-2011-2192',
 'KSC-2011-2453',
 'KSC-2011-2198',
 'KSC-2011-2452',
 'KSC-2011-2197',
 'KSC-2011-2457',
 'KSC-2011-1960',
 'KSC-2011-2455',
 'KSC-2011-2199',
 'KSC-2011-2450',
 'KSC-2011-2196',
 'KSC-2011-2190',
 'A Drier Future Sets the Stage for More Wildfires',
 'New Look at Gravity Data Sheds Light on Ocean and Climate',
 'NASA Science Live: Climate Edition - Innovations for a Sustainable Future [Episode 60]',
 'KSC-2011-1971',
 'KSC-2011-1970',
 'KSC-2011-1963',
 'KSC-2011-1961',
 'KSC-2011-1964',
 'KSC-2011-2188',
 'KSC-2011-1965',
 'KSC-2011-1967',
 'KSC-2011-1968',
 'KSC-2011-1966',
 'KSC-2011-1962',
 'KSC-2011-1969',
 'PREFIRE: A Mission to Better Understand Earth’s Polar Regions (Mission Overview)',
 'NASA Science Live: Connected by Earth [Episode 31]',
 'NASA Evaluates New Threats to Earth’s Ozone Layer']

In [22]:
keywords

[['NASA', 'NASA Administrator Bill Nelson', 'Climate Change'],
 ['We Asked A NASA Expert',
  'Climate Change',
  'Global Warming',
  'Earth',
  'Greenhouse Gases'],
 ['Precipitation', 'Sea Level Rise', 'Climate Change', 'Food Supply', 'Earth'],
 ['Earth',
  'Landsat',
  'New York City',
  'Earth Science',
  'Climate Change',
  'MODIS'],
 ['Climate Change', 'Food Supply', 'Earth'],
 ['MSFC', 'Gary Jedlovec', 'Green Team', 'Climate Change'],
 ['Mars', 'Mars Global Surveyor MGS'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Mary W. Jackson NASA Headquarters',
  'Matthew Pearce',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Mary W. Jackson NASA Headquarters',
  'Matthew Pearce',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Jack Kaye',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'Cynthia Hall',
  'DC',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Kate Calvin',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Jack Kaye',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Kate Calvin',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Global Warming',
  'Temperature Trend',
  'Precipitation',
  'Climate Change',
  'Climate Patterns',
  'Earth'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Karen St. Germain',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Karen St. Germain',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington'],
 ['Climate Change Research Initiative (CCRI)',
  'DC',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington',
  'Yaítza Luna-Cruz'],
 ['Climate Change Research Initiative (CCRI)',
  'Cynthia Hall',
  'DC',
  'Mary W. Jackson NASA Headquarters',
  'NASA Early Career Research Program (ECR)',
  'Washington',
  'Yaítza Luna-Cruz'],
 ['Carbon Release',
  'Carbon Sink',
  'Climate',
  'Climate Indicators',
  'Organic Matter',
  'Permafrost',
  'Arctic',
  'Climate Change',
  'Earth',
  'Wildfires'],
 ['Sea Ice',
  'Temperature',
  'Temperature Trend',
  'Climate Indicators',
  'Climate Change',
  'Earth'],
 ['climate',
  'earth',
  'taira allen',
  'kate calvin',
  'michelle hawkins',
  'climate change',
  'extreme weather',
  'NSL',
  'NASA Science Live'],
 ['Climate Change', 'Earth'],
 ['NSL',
  'NASA Science Live',
  'Climate',
  'Climate Change',
  'Megan Cruz',
  'Gavin Schidt',
  'Kate Calvin',
  'Global Temperatures'],
 ['Himalaya',
  'Watershed',
  'Glacial Landforms',
  'Climate Change',
  'Earth',
  'Floods',
  'Freshwater'],
 ['Earth Science',
  'Vice President',
  'Kamala Harris',
  'NASA Administrator',
  'Bill Nelson',
  'Goddard Visit',
  'Tour',
  'climate change',
  'climate studies',
  'GSFC'],
 ['ScienceCasts',
  'ISS',
  'International Space Station',
  'photography',
  'astronaut',
  'climate change',
  'disaster response'],
 ['Physical Oceanography',
  'Oceans',
  'Ocean Circulation',
  'Thermohaline Circulation',
  'Salinity',
  'Aquarius',
  'Climate Change',
  'Earth Science Week',
  'Earth'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['Landsat', 'Islands', 'Sea Level Rise', 'Climate Change', 'Earth'],
 ['Atmospheric Science',
  'Aerosols',
  'Climate Change',
  'Greenhouse Gases',
  'Earth',
  'mini-LHR',
  'AERONET',
  'Aerosols Optical Depth'],
 ['NDVI', 'Arctic', 'Climate Change', 'Vegetation Growth', 'Earth'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['Drought',
  'Fire Management',
  'Human Geography',
  'Natural Hazards',
  'Fires',
  'Climate Change',
  'Earth',
  'Freshwater'],
 ['Earth', 'Gravity Recovery and Climate Experiment GRACE'],
 ['Jasmine Hopkins',
  'Dr. Kate Calvin',
  'Dan Lockney',
  'NASA',
  'Climate',
  'Climate Change',
  'Earth Science',
  'Spinoff Technology',
  'Sustainable',
  'Innovations',
  'Green Technology',
  'Recycle',
  'Lunarecycle challenge',
  'Renewable energies',
  'Wildfires',
  'Beaver dam',
  'Agriculture',
  'NSL',
  'NASA Science Live'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['ELV, Delta II, science, research, climate change, Earth mission'],
 ['NASA',
  'JPL',
  'Jet Propulsion Laboratory',
  'Jet Propulsion Lab',
  'University of Wisconsin-Madison',
  'weather models',
  'climate',
  'climate change',
  'climate models',
  'climate predictions',
  'weather predictions',
  'forecast',
  'forecast predictions',
  'poles',
  'polar regions',
  'Arctic',
  'Antarctic',
  'sun',
  'space',
  'energy',
  'global warming',
  'heat loss',
  'rising sea levels',
  'satellites',
  'CubeSats',
  'polar orbit',
  'wavelengths',
  'infrared',
  'far-infrared',
  'far infrared',
  'spectrometer',
  'instrument',
  'spectrum',
  'rainbow',
  "Tristan L'Ecuyer",
  'Natasha Vos',
  'Sharmila Padmanabhan'],
 ['NASA Science Live',
  'NSL',
  'Kimberley R. Miner',
  'Lesley Ott',
  'Equisha Glenn',
  '#askNASA',
  '#ConnectedByEarth',
  '@NASAEarth',
  '@NASAClimate',
  'Climate change',
  'Global warming',
  'Earth Day'],
 ['Antarctic',
  'Earth',
  'Ozone Hole',
  'Ozone Depletion',
  'Ozone',
  'Climate Change',
  'Atmospheric Science',
  'Montreal Protocol']]

In [10]:
import pandas as pd

In [11]:
df = pd.DataFrame({
    'title': titles,
    'date_created': datesCreated,
    'keywords': keywords,
    'media_type': mediaTypes,
    'description': descriptions,
    'nasa_id': nasaIds,
    'links': links
})

In [12]:
df

,title,date_created,keywords,media_type,description,nasa_id,links
0,NASA Administrator Bill Nelson | Answering Cli...,2024-09-30T00:00:00Z,"[NASA, NASA Administrator Bill Nelson, Climate...",video,NASA Administrator Bill Nelson speaks to the p...,NASA Administrator Bill Nelson - Answering Cli...,[{'href': 'https://images-assets.nasa.gov/vide...
1,Is Climate Change the Same as Global Warming? ...,2023-07-27T00:00:00Z,"[We Asked A NASA Expert, Climate Change, Globa...",video,Is climate change the same as global warming? ...,Is Climate Change the Same as Global Warming_ ...,[{'href': 'https://images-assets.nasa.gov/vide...
2,Ask A Climate Scientist - Climate Change and H...,2013-12-03T00:00:00Z,"[Precipitation, Sea Level Rise, Climate Change...",video,How does climate change affect humans? That's ...,GSFC_20131203_AACS_m11426_Affect_Humans,[{'href': 'https://images-assets.nasa.gov/vide...
3,NASA Scientists Help Citites Prepare for Clima...,2016-11-16T00:00:00Z,"[Earth, Landsat, New York City, Earth Science,...",video,Researchers and city officials from two of the...,GSFC_20161116_Climate_m12426_Change,[{'href': 'https://images-assets.nasa.gov/vide...
4,Ask A Climate Scientist - Food Production,2013-09-18T00:00:00Z,"[Climate Change, Food Supply, Earth]",video,Will climate change drastically reduce our foo...,GSFC_20130918_AACS_m11356_Food,[{'href': 'https://images-assets.nasa.gov/vide...
...,...,...,...,...,...,...,...
95,KSC-2011-1962,2011-03-01T00:00:00Z,"[ELV, Delta II, science, research, climate cha...",image,"VANDENBERG AIR FORCE BASE, Calif. -- The first...",KSC-2011-1962,[{'href': 'https://images-assets.nasa.gov/imag...
96,KSC-2011-1969,2011-03-01T00:00:00Z,"[ELV, Delta II, science, research, climate cha...",image,"VANDENBERG AIR FORCE BASE, Calif. -- Technicia...",KSC-2011-1969,[{'href': 'https://images-assets.nasa.gov/imag...
97,PREFIRE: A Mission to Better Understand Earth’...,2024-05-16T00:00:00Z,"[NASA, JPL, Jet Propulsion Laboratory, Jet Pro...",video,NASA’s PREFIRE mission aims to improve global ...,JPL-20240516-PRFIREf-0001-PREFIRE Overview Video,[{'href': 'https://images-assets.nasa.gov/vide...
98,NASA Science Live: Connected by Earth [Episode...,2021-04-22T00:00:00Z,"[NASA Science Live, NSL, Kimberley R. Miner, L...",video,"This year at NASA, Earth Day is about connecti...",GSFC_20210422_NSL_Ep31,[{'href': 'https://images-assets.nasa.gov/vide...
99,NASA Evaluates New Threats to Earth’s Ozone Layer,2017-12-08T00:00:00Z,"[Antarctic, Earth, Ozone Hole, Ozone Depletion...",video,Scientists are closely monitoring positive sig...,GSFC_20171208_Ozone_m12797_Future,[{'href': 'https://images-assets.nasa.gov/vide...

In [26]:
from time import sleep
for i in range(0, 17):
    r = requests.get(f'http://images-api.nasa.gov/search?q={query}&page={i}')
    sleep(2)
    items = parsed['collection']['items']

    for i in items:
        data = i['data']
        for i in data:
            title = (i['title'])
            titles.append(title)

    for i in items:
        data = i['data']
        for i in data:
            dateCreated = (i['date_created'])
            datesCreated.append(dateCreated)

    for i in items:
        data = i['data']
        for i in data:
            mediaType = (i['media_type'])
            mediaTypes.append(mediaType)

    for i in items:
        data = i['data']
        for i in data:
            description = (i['description'])
            descriptions.append(description)

    for i in items:
        data = i['data']
        for i in data:
            nasaId = (i['nasa_id'])
            nasaIds.append(nasaId)

    for i in items:
        data = i['data']
        for i in data:
            try:
                keyword = (i['keywords'])
                keywords.append(keyword)
            except:
                keyword = 'n/a'
                keywords.append(keyword)

    for i in items:
        try:
            link = i['links']
            links.append(link)
        except:
            link = 'n/a'
            links.append(link)

In [27]:
r

In [28]:
print(len(titles), len(datesCreated), len(keywords), len(mediaTypes), len(descriptions), len(nasaIds), len(links))

1700 1700 1700 1700 1700 1700 1700

In [29]:
df = pd.DataFrame({
    'title': titles,
    'date_created': datesCreated,
    'keywords': keywords,
    'media_type': mediaTypes,
    'description': descriptions,
    'nasa_id': nasaIds,
    'links': links
})

In [30]:
df

,title,date_created,keywords,media_type,description,nasa_id,links
0,NASA Administrator Bill Nelson | Answering Cli...,2024-09-30T00:00:00Z,"[NASA, NASA Administrator Bill Nelson, Climate...",video,NASA Administrator Bill Nelson speaks to the p...,NASA Administrator Bill Nelson - Answering Cli...,[{'href': 'https://images-assets.nasa.gov/vide...
1,Is Climate Change the Same as Global Warming? ...,2023-07-27T00:00:00Z,"[We Asked A NASA Expert, Climate Change, Globa...",video,Is climate change the same as global warming? ...,Is Climate Change the Same as Global Warming_ ...,[{'href': 'https://images-assets.nasa.gov/vide...
2,Ask A Climate Scientist - Climate Change and H...,2013-12-03T00:00:00Z,"[Precipitation, Sea Level Rise, Climate Change...",video,How does climate change affect humans? That's ...,GSFC_20131203_AACS_m11426_Affect_Humans,[{'href': 'https://images-assets.nasa.gov/vide...
3,NASA Scientists Help Citites Prepare for Clima...,2016-11-16T00:00:00Z,"[Earth, Landsat, New York City, Earth Science,...",video,Researchers and city officials from two of the...,GSFC_20161116_Climate_m12426_Change,[{'href': 'https://images-assets.nasa.gov/vide...
4,Ask A Climate Scientist - Food Production,2013-09-18T00:00:00Z,"[Climate Change, Food Supply, Earth]",video,Will climate change drastically reduce our foo...,GSFC_20130918_AACS_m11356_Food,[{'href': 'https://images-assets.nasa.gov/vide...
...,...,...,...,...,...,...,...
1695,KSC-2011-1962,2011-03-01T00:00:00Z,"[ELV, Delta II, science, research, climate cha...",image,"VANDENBERG AIR FORCE BASE, Calif. -- The first...",KSC-2011-1962,[{'href': 'https://images-assets.nasa.gov/imag...
1696,KSC-2011-1969,2011-03-01T00:00:00Z,"[ELV, Delta II, science, research, climate cha...",image,"VANDENBERG AIR FORCE BASE, Calif. -- Technicia...",KSC-2011-1969,[{'href': 'https://images-assets.nasa.gov/imag...
1697,PREFIRE: A Mission to Better Understand Earth’...,2024-05-16T00:00:00Z,"[NASA, JPL, Jet Propulsion Laboratory, Jet Pro...",video,NASA’s PREFIRE mission aims to improve global ...,JPL-20240516-PRFIREf-0001-PREFIRE Overview Video,[{'href': 'https://images-assets.nasa.gov/vide...
1698,NASA Science Live: Connected by Earth [Episode...,2021-04-22T00:00:00Z,"[NASA Science Live, NSL, Kimberley R. Miner, L...",video,"This year at NASA, Earth Day is about connecti...",GSFC_20210422_NSL_Ep31,[{'href': 'https://images-assets.nasa.gov/vide...
1699,NASA Evaluates New Threats to Earth’s Ozone Layer,2017-12-08T00:00:00Z,"[Antarctic, Earth, Ozone Hole, Ozone Depletion...",video,Scientists are closely monitoring positive sig...,GSFC_20171208_Ozone_m12797_Future,[{'href': 'https://images-assets.nasa.gov/vide...

In [13]:
import csv
df.to_csv('nasa_data_page1.csv')